# Asteroid magic nums
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# sprite line width
LINE_WIDTH = 2

# player magic nums
PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300

#screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
